providers = ["node"]

[phases.setup]
nixPkgs = ['nodejs']
cmds = [
  "corepack enable",
  "corepack prepare pnpm@10.7.0 --activate"
]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm run build:server"
]

[start]
cmd = "cd examples/showcase/server && pnpm start"

