providers = ["node"]

[phases.setup]
nixPkgs = ['nodejs']
cmds = [
  "corepack enable",
  "corepack prepare pnpm@10.7.0 --activate",
  "export PATH=\"$HOME/.local/share/pnpm:$PATH\"",
  "pnpm --version"
]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm run build:server"
]

[start]
cmd = "cd examples/showcase/server && pnpm start"

